import type { Student } from "../types";

export const mockStudents: Student[] = [
  {
    id: "1329900111111",
    studentId: "0001",
    classLevel: "ม.6",
    classRoom: "1",
    gender: "ชาย",
    title: "นาย",
    firstName: "ภาคิน",
    lastName: "จงเจริญ",
    birthDate: "2007-02-15",
    weight: 68,
    height: 178,
    bloodGroup: "O",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "12",
      moo: "3",
      street: "ถนนมิตรภาพ",
      subDistrict: "ในเมือง",
      district: "เมือง",
      province: "นครราชสีมา",
    },
    parent: {
      fullName: "นางสมศรี จงเจริญ",
      occupation: "ค้าขาย",
      relationship: "มารดา",
    },
    father: { fullName: "นายสมศักดิ์ จงเจริญ", occupation: "เกษตรกร" },
    mother: { fullName: "นางสมศรี จงเจริญ", occupation: "ค้าขาย" },
    disability: "ไม่มี",
    insurance: "ทำประกัน",
  },
  {
    id: "1329900222222",
    studentId: "0002",
    classLevel: "ม.6",
    classRoom: "1",
    gender: "หญิง",
    title: "นางสาว",
    firstName: "กวินนา",
    lastName: "ศรีสุข",
    birthDate: "2007-03-20",
    weight: 55,
    height: 165,
    bloodGroup: "A",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "45/1",
      moo: "7",
      street: "ถนนแจ้งวัฒนะ",
      subDistrict: "ทุ่งสองห้อง",
      district: "หลักสี่",
      province: "กรุงเทพมหานคร",
    },
    parent: {
      fullName: "นายมาโนช ศรีสุข",
      occupation: "รับราชการ",
      relationship: "บิดา",
    },
    father: { fullName: "นายมาโนช ศรีสุข", occupation: "รับราชการ" },
    mother: { fullName: "นางวิภา ศรีสุข", occupation: "แม่บ้าน" },
    disability: "ไม่มี",
    insurance: "ไม่ได้ทำประกัน",
  },
  {
    id: "1329900333333",
    studentId: "0003",
    classLevel: "ม.5",
    classRoom: "2",
    gender: "ชาย",
    title: "นาย",
    firstName: "ธนภัทร",
    lastName: "พิทักษ์ไทย",
    birthDate: "2008-01-30",
    weight: 62,
    height: 172,
    bloodGroup: "B",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "222",
      moo: "1",
      street: "ถนนพหลโยธิน",
      subDistrict: "คลองหนึ่ง",
      district: "คลองหลวง",
      province: "ปทุมธานี",
    },
    parent: {
      fullName: "นางจินตนา พิทักษ์ไทย",
      occupation: "พนักงานบริษัท",
      relationship: "มารดา",
    },
    father: { fullName: "นายธีรเดช พิทักษ์ไทย", occupation: "วิศวกร" },
    mother: { fullName: "นางจินตนา พิทักษ์ไทย", occupation: "พนักงานบริษัท" },
    disability: "ไม่มี",
    insurance: "ทำประกัน",
  },
  {
    id: "1329900444444",
    studentId: "0004",
    classLevel: "ม.5",
    classRoom: "2",
    gender: "หญิง",
    title: "นางสาว",
    firstName: "ปณาลี",
    lastName: "วัฒนกิจ",
    birthDate: "2008-05-18",
    weight: 58,
    height: 168,
    bloodGroup: "AB",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "88/8",
      moo: "9",
      street: "ถนนสุขุมวิท",
      subDistrict: "บางปูใหม่",
      district: "เมือง",
      province: "สมุทรปราการ",
    },
    parent: {
      fullName: "นางสาวอรุณี วัฒนกิจ",
      occupation: "ธุรกิจส่วนตัว",
      relationship: "มารดา",
    },
    father: { fullName: "ไม่ปรากฎ", occupation: "-" },
    mother: { fullName: "นางสาวอรุณี วัฒนกิจ", occupation: "ธุรกิจส่วนตัว" },
    disability: "ไม่มี",
    insurance: "ทำประกัน",
  },
  {
    id: "1329900555555",
    studentId: "0005",
    classLevel: "ม.4",
    classRoom: "3",
    gender: "ชาย",
    title: "เด็กชาย",
    firstName: "ณัฐวุฒิ",
    lastName: "แซ่ลิ้ม",
    birthDate: "2009-08-25",
    weight: 59,
    height: 169,
    bloodGroup: "O",
    religion: "พุทธ",
    ethnicity: "ไทย-จีน",
    nationality: "ไทย",
    address: {
      houseNumber: "150",
      moo: "-",
      street: "ถนนเยาวราช",
      subDistrict: "สัมพันธวงศ์",
      district: "สัมพันธวงศ์",
      province: "กรุงเทพมหานคร",
    },
    parent: {
      fullName: "นายกิตติ แซ่ลิ้ม",
      occupation: "เจ้าของร้านอาหาร",
      relationship: "บิดา",
    },
    father: { fullName: "นายกิตติ แซ่ลิ้ม", occupation: "เจ้าของร้านอาหาร" },
    mother: { fullName: "นางมณี แซ่ลิ้ม", occupation: "เจ้าของร้านอาหาร" },
    disability: "ไม่มี",
    insurance: "ไม่ได้ทำประกัน",
  },
  {
    id: "1329900666666",
    studentId: "0006",
    classLevel: "ม.6",
    classRoom: "2",
    gender: "หญิง",
    title: "นางสาว",
    firstName: "พิมพ์ชนก",
    lastName: "อิสระ",
    birthDate: "2007-06-11",
    weight: 52,
    height: 162,
    bloodGroup: "B",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "34",
      moo: "5",
      street: "ถนนเพชรเกษม",
      subDistrict: "อ้อมน้อย",
      district: "กระทุ่มแบน",
      province: "สมุทรสาคร",
    },
    parent: {
      fullName: "นายประเสริฐ อิสระ",
      occupation: "พนักงานโรงงาน",
      relationship: "บิดา",
    },
    father: { fullName: "นายประเสริฐ อิสระ", occupation: "พนักงานโรงงาน" },
    mother: { fullName: "นางสมใจ อิสระ", occupation: "แม่บ้าน" },
    disability: "ไม่มี",
    insurance: "ทำประกัน",
  },
  {
    id: "1329900777777",
    studentId: "0007",
    classLevel: "ม.5",
    classRoom: "1",
    gender: "ชาย",
    title: "นาย",
    firstName: "ศุภกร",
    lastName: "บุญมี",
    birthDate: "2008-11-01",
    weight: 70,
    height: 180,
    bloodGroup: "A",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "191",
      moo: "11",
      street: "ถนนมิตรภาพ",
      subDistrict: "จอหอ",
      district: "เมือง",
      province: "นครราชสีมา",
    },
    parent: {
      fullName: "นางวันเพ็ญ บุญมี",
      occupation: "ข้าราชการครู",
      relationship: "มารดา",
    },
    father: { fullName: "ร.ต.อ. อาทิตย์ บุญมี", occupation: "ตำรวจ" },
    mother: { fullName: "นางวันเพ็ญ บุญมี", occupation: "ข้าราชการครู" },
    disability: "ไม่มี",
    insurance: "ทำประกัน",
  },
  {
    id: "1329900888888",
    studentId: "0008",
    classLevel: "ม.4",
    classRoom: "1",
    gender: "หญิง",
    title: "เด็กหญิง",
    firstName: "อริสรา",
    lastName: "ทองดี",
    birthDate: "2009-09-09",
    weight: 50,
    height: 160,
    bloodGroup: "O",
    religion: "อิสลาม",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "78/2",
      moo: "2",
      street: "ถนนราษฎร์อุทิศ",
      subDistrict: "หาดใหญ่",
      district: "หาดใหญ่",
      province: "สงขลา",
    },
    parent: {
      fullName: "นายอาซัน ทองดี",
      occupation: "ค้าขาย",
      relationship: "บิดา",
    },
    father: { fullName: "นายอาซัน ทองดี", occupation: "ค้าขาย" },
    mother: { fullName: "นางฟาติมา ทองดี", occupation: "ค้าขาย" },
    disability: "ไม่มี",
    insurance: "ไม่ได้ทำประกัน",
  },
  {
    id: "1329900999999",
    studentId: "0009",
    classLevel: "ม.6",
    classRoom: "3",
    gender: "ชาย",
    title: "นาย",
    firstName: "เจษฎา",
    lastName: "รักชาติ",
    birthDate: "2007-07-07",
    weight: 65,
    height: 174,
    bloodGroup: "B",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "55",
      moo: "6",
      street: "ถนนรอบเมือง",
      subDistrict: "หมากแข้ง",
      district: "เมือง",
      province: "อุดรธานี",
    },
    parent: {
      fullName: "นายอำนาจ รักชาติ",
      occupation: "ทำไร่",
      relationship: "บิดา",
    },
    father: { fullName: "นายอำนาจ รักชาติ", occupation: "ทำไร่" },
    mother: { fullName: "นางปราณี รักชาติ", occupation: "ทำนา" },
    disability: "ไม่มี",
    insurance: "ทำประกัน",
  },
  {
    id: "1329901010101",
    studentId: "0010",
    classLevel: "ม.5",
    classRoom: "3",
    gender: "หญิง",
    title: "นางสาว",
    firstName: "นลินี",
    lastName: "สุขเกษม",
    birthDate: "2008-04-12",
    weight: 54,
    height: 166,
    bloodGroup: "A",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "210/5",
      moo: "4",
      street: "ถนนชยางกูร",
      subDistrict: "ในเมือง",
      district: "เมือง",
      province: "อุบลราชธานี",
    },
    parent: {
      fullName: "นางนภา สุขเกษม",
      occupation: "พยาบาล",
      relationship: "มารดา",
    },
    father: { fullName: "นายแพทย์วิรัช สุขเกษม", occupation: "แพทย์" },
    mother: { fullName: "นางนภา สุขเกษม", occupation: "พยาบาล" },
    disability: "ด้านการเรียนรู้",
    insurance: "ทำประกัน",
  },
  {
    id: "1329901111112",
    studentId: "0011",
    classLevel: "ม.4",
    classRoom: "2",
    gender: "ชาย",
    title: "เด็กชาย",
    firstName: "ปองพล",
    lastName: "อดิศัย",
    birthDate: "2009-12-01",
    weight: 60,
    height: 170,
    bloodGroup: "O",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "111",
      moo: "1",
      street: "ถนนท่าแพ",
      subDistrict: "ช้างม่อย",
      district: "เมือง",
      province: "เชียงใหม่",
    },
    parent: {
      fullName: "นายบัญชา อดิศัย",
      occupation: "สถาปนิก",
      relationship: "บิดา",
    },
    father: { fullName: "นายบัญชา อดิศัย", occupation: "สถาปนิก" },
    mother: { fullName: "นางศิริพร อดิศัย", occupation: "มัณฑนากร" },
    disability: "ไม่มี",
    insurance: "ไม่ได้ทำประกัน",
  },
  {
    id: "1329901212121",
    studentId: "0012",
    classLevel: "ม.6",
    classRoom: "1",
    gender: "หญิง",
    title: "นางสาว",
    firstName: "รินรดา",
    lastName: "กิจจา",
    birthDate: "2007-10-22",
    weight: 53,
    height: 163,
    bloodGroup: "AB",
    religion: "คริสต์",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "99/10",
      moo: "8",
      street: "ถนนรัตนาธิเบศร์",
      subDistrict: "บางกระสอ",
      district: "เมือง",
      province: "นนทบุรี",
    },
    parent: {
      fullName: "นางแอนนา กิจจา",
      occupation: "ครู",
      relationship: "มารดา",
    },
    father: { fullName: "นายยอแซฟ กิจจา", occupation: "พนักงานธนาคาร" },
    mother: { fullName: "นางแอนนา กิจจา", occupation: "ครู" },
    disability: "ไม่มี",
    insurance: "ทำประกัน",
  },
  {
    id: "1329901313131",
    studentId: "0013",
    classLevel: "ม.5",
    classRoom: "4",
    gender: "ชาย",
    title: "นาย",
    firstName: "วีรภัทร",
    lastName: "มีทรัพย์",
    birthDate: "2008-08-14",
    weight: 66,
    height: 176,
    bloodGroup: "B",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "78",
      moo: "12",
      street: "ถนนเลี่ยงเมือง",
      subDistrict: "ตลาด",
      district: "เมือง",
      province: "มหาสารคาม",
    },
    parent: {
      fullName: "นายสมบัติ มีทรัพย์",
      occupation: "รับเหมาก่อสร้าง",
      relationship: "บิดา",
    },
    father: { fullName: "นายสมบัติ มีทรัพย์", occupation: "รับเหมาก่อสร้าง" },
    mother: { fullName: "นางสมร มีทรัพย์", occupation: "ค้าขาย" },
    disability: "ไม่มี",
    insurance: "ทำประกัน",
  },
  {
    id: "1329901414141",
    studentId: "0014",
    classLevel: "ม.4",
    classRoom: "4",
    gender: "หญิง",
    title: "เด็กหญิง",
    firstName: "สุพิชชา",
    lastName: "งามวิไล",
    birthDate: "2009-06-28",
    weight: 51,
    height: 161,
    bloodGroup: "A",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "234",
      moo: "3",
      street: "ถนนเทพารักษ์",
      subDistrict: "สำโรงเหนือ",
      district: "เมือง",
      province: "สมุทรปราการ",
    },
    parent: {
      fullName: "นางยุพา งามวิไล",
      occupation: "พนักงานบริษัท",
      relationship: "มารดา",
    },
    father: { fullName: "นายเกรียงไกร งามวิไล", occupation: "พนักงานบริษัท" },
    mother: { fullName: "นางยุพา งามวิไล", occupation: "พนักงานบริษัท" },
    disability: "ไม่มี",
    insurance: "ไม่ได้ทำประกัน",
  },
  {
    id: "1329901515151",
    studentId: "0015",
    classLevel: "ม.6",
    classRoom: "2",
    gender: "ชาย",
    title: "นาย",
    firstName: "อัครเดช",
    lastName: "โพธิ์งาม",
    birthDate: "2007-04-05",
    weight: 72,
    height: 182,
    bloodGroup: "O",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "56/7",
      moo: "10",
      street: "ถนนบรมราชชนนี",
      subDistrict: "ศาลาธรรมสพน์",
      district: "ทวีวัฒนา",
      province: "กรุงเทพมหานคร",
    },
    parent: {
      fullName: "นายวิเชียร โพธิ์งาม",
      occupation: "ช่างยนต์",
      relationship: "บิดา",
    },
    father: { fullName: "นายวิเชียร โพธิ์งาม", occupation: "ช่างยนต์" },
    mother: { fullName: "นางลำดวน โพธิ์งาม", occupation: "แม่บ้าน" },
    disability: "ไม่มี",
    insurance: "ทำประกัน",
  },
  {
    id: "1329901616161",
    studentId: "0016",
    classLevel: "ม.5",
    classRoom: "1",
    gender: "หญิง",
    title: "นางสาว",
    firstName: "จิรัชญา",
    lastName: "เด่นดี",
    birthDate: "2008-02-29",
    weight: 56,
    height: 167,
    bloodGroup: "B",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "1/1",
      moo: "1",
      street: "ถนนพระราม 2",
      subDistrict: "แสมดำ",
      district: "บางขุนเทียน",
      province: "กรุงเทพมหานคร",
    },
    parent: {
      fullName: "นางดวงพร เด่นดี",
      occupation: "ธุรกิจส่วนตัว",
      relationship: "มารดา",
    },
    father: { fullName: "ไม่ปรากฎ", occupation: "-" },
    mother: { fullName: "นางดวงพร เด่นดี", occupation: "ธุรกิจส่วนตัว" },
    disability: "ไม่มี",
    insurance: "ทำประกัน",
  },
  {
    id: "1329901717171",
    studentId: "0017",
    classLevel: "ม.4",
    classRoom: "3",
    gender: "ชาย",
    title: "เด็กชาย",
    firstName: "ชินวัฒน์",
    lastName: "เรืองฤทธิ์",
    birthDate: "2009-10-10",
    weight: 58,
    height: 168,
    bloodGroup: "A",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "888",
      moo: "8",
      street: "ถนนวิภาวดีรังสิต",
      subDistrict: "ตลาดบางเขน",
      district: "หลักสี่",
      province: "กรุงเทพมหานคร",
    },
    parent: {
      fullName: "พล.อ.อ. ชาตรี เรืองฤทธิ์",
      occupation: "รับราชการ",
      relationship: "บิดา",
    },
    father: { fullName: "พล.อ.อ. ชาตรี เรืองฤทธิ์", occupation: "รับราชการ" },
    mother: { fullName: "คุณหญิงวราภรณ์ เรืองฤทธิ์", occupation: "แม่บ้าน" },
    disability: "ไม่มี",
    insurance: "ไม่ได้ทำประกัน",
  },
  {
    id: "1329901818181",
    studentId: "0018",
    classLevel: "ม.6",
    classRoom: "3",
    gender: "หญิง",
    title: "นางสาว",
    firstName: "เบญจวรรณ",
    lastName: "จันทร",
    birthDate: "2007-09-18",
    weight: 60,
    height: 170,
    bloodGroup: "O",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "43/2",
      moo: "7",
      street: "ถนนศรีนครินทร์",
      subDistrict: "หนองบอน",
      district: "ประเวศ",
      province: "กรุงเทพมหานคร",
    },
    parent: {
      fullName: "นางพยอม จันทร",
      occupation: "พนักงานออฟฟิศ",
      relationship: "มารดา",
    },
    father: { fullName: "นายสมเกียรติ จันทร", occupation: "พนักงานออฟฟิศ" },
    mother: { fullName: "นางพยอม จันทร", occupation: "พนักงานออฟฟิศ" },
    disability: "ไม่มี",
    insurance: "ทำประกัน",
  },
  {
    id: "1329901919191",
    studentId: "0019",
    classLevel: "ม.5",
    classRoom: "2",
    gender: "ชาย",
    title: "นาย",
    firstName: "ภูริณัฐ",
    lastName: "ศิลาชัย",
    birthDate: "2008-06-21",
    weight: 63,
    height: 173,
    bloodGroup: "B",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "33/3",
      moo: "3",
      street: "ถนนลาดพร้าว",
      subDistrict: "วังทองหลาง",
      district: "วังทองหลาง",
      province: "กรุงเทพมหานคร",
    },
    parent: {
      fullName: "นายวิโรจน์ ศิลาชัย",
      occupation: "นักดนตรี",
      relationship: "บิดา",
    },
    father: { fullName: "นายวิโรจน์ ศิลาชัย", occupation: "นักดนตรี" },
    mother: { fullName: "นางปาริฉัตร ศิลาชัย", occupation: "แม่บ้าน" },
    disability: "ไม่มี",
    insurance: "ทำประกัน",
  },
  {
    id: "1329902020202",
    studentId: "0020",
    classLevel: "ม.4",
    classRoom: "1",
    gender: "หญิง",
    title: "เด็กหญิง",
    firstName: "อนัญญา",
    lastName: "วงศ์สุวรรณ",
    birthDate: "2009-11-30",
    weight: 52,
    height: 164,
    bloodGroup: "AB",
    religion: "พุทธ",
    ethnicity: "ไทย",
    nationality: "ไทย",
    address: {
      houseNumber: "789",
      moo: "9",
      street: "ถนนรามคำแหง",
      subDistrict: "หัวหมาก",
      district: "บางกะปิ",
      province: "กรุงเทพมหานคร",
    },
    parent: {
      fullName: "นางอมรา วงศ์สุวรรณ",
      occupation: "อาจารย์มหาวิทยาลัย",
      relationship: "มารดา",
    },
    father: {
      fullName: "นายธิติ วงศ์สุวรรณ",
      occupation: "อาจารย์มหาวิทยาลัย",
    },
    mother: {
      fullName: "นางอมรา วงศ์สุวรรณ",
      occupation: "อาจารย์มหาวิทยาลัย",
    },
    disability: "ไม่มี",
    insurance: "ทำประกัน",
  },
];
